config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "en", to: "pages#en"
  get "sobre", to: "pages#sobre"

  # Read all
  root to: 'artists#index'
  # Create
  get    "artists/new",      to: "artists#new",  as: :new_artist
  post   "artists",          to: "artists#create"
  # Read one - The `show` route needs to be *after* `new` route.
  get '/:slug', to: 'artists#show', as: :artist
  # Update
  get '/:slug/edit', to: 'artists#edit'
  patch  '/:slug',      to: "artists#update"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many_attached :photos
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
skip_before_action :authenticate_user!, :verify_authenticity_token
before_action :set_artist, only: [:show, :edit, :update]


  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
  end

  def index
    @everybody = Artist.all
    @artists = @everybody.sort_alphabetical_by(&:name)
  end

  def show
  end

  def edit
  end

  def update
    @artist.update(artist_params)
  end

  private

  def set_artist
    @artist = Artist.friendly.find_by!(slug: params[:slug])
  end

  def artist_params
    params.require(:artist).permit(:name, :bio, :about, :exposicao, :critica, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def en
    @artists = Artist.all
  end

  def sobre
    @artist = Artist.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/artists/_form.html.erb
<div class="container" style="max-width:1000px; margin:auto;">

  <%= simple_form_for(@artist) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :bio, as: :text %>
      <%= f.input :about, as: :text %>
      <%= f.input :exposicao, as: :text %>
      <%= f.input :critica, as: :text %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Criar artista", class: 'btn-formulario' %>
    </div>

  <% end %>

</div>

app/views/artists/edit.html.erb
<div class="navigation">
  <div class="martir-container d-flex justify-content-between align-items-center">
      <%= link_to image_tag("martir_logo_sm.svg"), root_path %>
      <div class="menu m-0 p-0 d-flex">
        <%# link_to "SOBRE", sobre_path, class:"hover-underline-animation" %>
        <%# link_to "INSTITUTO TRAGALUZ", sobre_path, class:"hover-underline-animation" %>
      </div>
    </div>
</div>

<div class="martir-container d-flex" style="padding-top: 120px;">
  <h4 style="margin-right: 32px;">Editar</h4>
  <div class="container" style="max-width:1000px; margin:auto;">
    <%= simple_form_for(@artist) do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :bio, as: :text %>
        <%= f.input :about, as: :text %>
        <%= f.input :exposicao, as: :text %>
        <%= f.input :critica, as: :text %>
        <% unless @artist.photos.attached? %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <% end %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Atualizar", class: 'btn-formulario' %>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/index.html.erb
<div class="hide navigation" data-controller="navtitle" data-action="scroll@window->navtitle#updateTitle" data-navtitle-target="navigation">
  <div class="martir-container d-flex justify-content-between align-items-center">
      <%= link_to image_tag("martir_logo_sm.svg"), root_path %>
      <div class="menu m-0 p-0 d-flex">
        <%= link_to "SOBRE", sobre_path, class:"hover-underline-animation" %>
        <%= link_to "INSTITUTO TRAGALUZ", sobre_path, class:"hover-underline-animation" %>

        <div class="switch-language d-flex nav nav-pills" id="pills-tab" role="tablist">
          <div class="nav-item" role="presentation">
            <button class="nav-link hover-underline-animation active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true" style="color:black;">PT</button>
          </div>
          <div style="padding-left:4px;"> | </div>
          <div class="nav-item" role="presentation">
            <button class="nav-link hover-underline-animation" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false" style="color:black;">EN</button>
          </div>
        </div>

      </div>
    </div>
</div>


   <div class="martir-container d-flex justify-content-center pt-3 pb-3 mb-0">
    <%= image_tag "martir_logo_footer.svg", class: "main-title-svg" %>
  </div>

  <%# div comentada sem o javascript do titulo  %>
  <%# <div class="main-title scrolled pt-3 pb-0 mb-0" data-controller="navtitle" data-action="load@window->navtitle#minimalTitle" data-action="scroll@window->navtitle#backTitle" data-navtitle-target="martir"> MARTIR </div>
  <%# ----------------------------------------  %>


  <div class="hero d-flex justify-content-center align-items-end">
    <%# image_tag "martir-hero02.png" %>
    <%= image_tag "martir.webp" %>
  </div>



  <div class="tab-content p-0 mt-3" id="pills-tabContent">
  <%# conteudo em portugues %>
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

      <div class="martir-container main-subtitle d-flex justify-content-between">
        <div class="title-mostra">
          <h2>Mostra de Arte <br>de Tiradentes</h2>
          <h3>COLEÇÃO TADEU BANDEIRA</h3>
        </div>
        <div class="about-martir">
          <p>Localizado na cidade histórica de Tiradentes, Martir foi especialmente delineado para acolher importantes exposições, como a mostra intitulada "Arte Mineira Contemporânea”. A exposição conta com obras de prestigiosos e talentosos artistas, parte da coleção "Tadeu Bandeira”, constituída a partir do olhar do colecionador para a produção mineira a partir dos anos 1970. O espaço pertence ao Instituto Tragaluz, uma associação civil de direito privado, sem fins lucrativos, que almeja com essas ações fomentar outras de natureza semelhante.</p>
        </div>
      </div>

      <div class="martir-container main-about d-none d-sm-flex justify-content-between align-items-end">
        <div class="about-bandeira">
          <p>"Em 1972, fui até a rodoviária e peguei um ônibus até Ouro Preto para conhecer Nello Nuno. Toquei a campainha da sua casa no Largo do Rosário, me apresentei como um simples colegial dos Irmãos Maristas, falei do meu interesse em adquirir um de seus quadros, ainda que com pequeno dinheiro de mesada. Compreendendo a situação, ele me recebeu gentilmente e trouxe até a mim um lindo pôr do sol em Ouro Preto, indagando se estariam bem oito parcelas. Tal pintura integra essa coleção ora aberta à visitação pública."
            <br><br> <span style="font-style:normal">— Tadeu Bandeira</span>
          </p>
        </div>
        <div class="about-images">
        </div>
      </div>

      <%# -------- mobile --------  %>
      <div class="martir-container d-sm-none main-about-mobile d-flex flex-column justify-content-between align-items-center">
        <div class="about-images-mobile">
        </div>
        <div class="about-bandeira-mobile">
          <p>"Em 1972, fui até a rodoviária e peguei um ônibus até Ouro Preto para conhecer Nello Nuno. Toquei a campainha da sua casa no Largo do Rosário, me apresentei como um simples colegial dos Irmãos Maristas, falei do meu interesse em adquirir um de seus quadros, ainda que com pequeno dinheiro de mesada. Compreendendo a situação, ele me recebeu gentilmente e trouxe até a mim um lindo pôr do sol em Ouro Preto, indagando se estariam bem oito parcelas. Tal pintura integra essa coleção ora aberta à visitação pública."
            <br><br> <span style="font-style:normal">— Tadeu Bandeira</span>
          </p>
        </div>
      </div>
      <%# ------------------------  %>


      <div class="breath"></div>


      <div class="d-flex loop justify-content-center align-items-center">
      </div>

      <div class="artistas-obras bg-cream d-flex justify-content-center align-items-center">
        <%= image_tag "artistas-obras.svg", class:"d-none d-lg-block artistas-obras-img-desktop" %>
        <%= image_tag "artistas-obras-mobile.svg", class:"d-block d-lg-none artistas-obras-img-mobile" %>
      </div>

      <div class="martir-container accordion accordion-flush" id="accordionFlushExample">

        <% @artists.each do |artist| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-heading<%= artist.id %>">
            <button class="artist-line accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= artist.id %>" aria-expanded="false" aria-controls="flush-collapse<%= artist.id %>">
              <%= artist.name %>
            </button>
          </h2>
          <div id="flush-collapse<%= artist.id %>" class="accordion-collapse collapse" aria-labelledby="flush-heading<%= artist.id %>" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body p-0 pt-4 pb-4 d-flex justify-content-between">
                <% if artist.photos.count >= 1 %>
                  <div class="artist-works d-flex align-items-start">
                    <% artist.photos.each do |photo| %>
                    <%= cl_image_tag photo.key %>
                    <% end %>
                  </div>
                <% end %>
                <div class="artist-bio">
                  <p><%= simple_format(artist.bio) %></p>
                  <% if artist.photos.count >= 1 && artist.detail == true %>
                      <br>
                      <span style="font-style: italic; font-size: 11px; text-transform:uppercase;">* detalhe de obra</span>
                      <br>
                  <% end %>
                  <br>
                  <%= link_to artist_path(artist) do %>
                  <span class="btn-vermais">VER MAIS</span> <%= image_tag('arrow.svg') %>
                  <% end %>
                </div>

              </div>

          </div>
        </div>
        <% end %>


      </div>

      <div class="martir-container box-tragaluz">
        <div class="d-flex justify-content-between box-tragaluz-content bg-cream p-4 p-sm-5" style="border-radius:24px;">

            <h3>INSTITUTO <br> TRAGALUZ</h3>

              <p>
                Como formar ideias, criar, criticar, crescer e, se necessário, transformá-las em "conhecimento"? E como "conhecer” se não estivermos inseridos em um processo educativo contínuo e multiforme, utilizando os mais diversos e diferentes recursos?
                <br><br>
                O Instituto Tragaluz colabora de forma prática e atuante com mostras artísticas e culturais, exposições, palestras, debates e uma série de iniciativas de cunho social e educacional com ações desde a Primeira Infância.
                <br><br>
                Localizado na cidade histórica de Tiradentes, trata-se de uma associação civil de direito privado, sem fins lucrativos, que almeja com essas ações fomentar outras de natureza semelhante, em pleno exercício de responsabilidade social e cidadania.
              </p>

        </div>
      </div>

    </div>
  <%# conteudo em ingles %>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="martir-container main-subtitle d-flex justify-content-between">
        <div class="title-mostra">
          <h2>Tiradentes <br>Art Show</h2>
          <h3>TADEU BANDEIRA COLLECTION</h3>
        </div>
        <div class="about-martir">
          <p>Located in the historic city of Tiradentes, Martir was specially designed to host important exhibitions, such as the exhibition entitled "Arte Mineira Contemporânea – Minas Gerais Contemporary Art". The exhibition features works of art by prestigious and talented artists, which are part of the "Tadeu Bandeira" collection, based on the collector's view of Minas Gerais art production from the 1970s onwards. Martir belongs to Tragaluz, a non-profit institute, whose actions aim to encourage others with a similar nature.</p>
        </div>
      </div>

      <div class="martir-container main-about d-none d-sm-flex justify-content-between align-items-end">
        <div class="about-bandeira">
          <p>"In 1972, I went to the bus station and took a bus to Ouro Preto to meet Nello. I rang the doorbell of his house in Largo do Rosario, introduced myself as a simple schoolboy, spoke of my interest in purchasing one of his paintings, even if that meant to spend my allowance money. Acknowledging the situation, he received me kindly and brought me a beautiful sunset in Ouro Preto painting, asking if eight installments would be fine. This painting is part of this collection now open to the public."
            <br><br> <span style="font-style:normal">— Tadeu Bandeira</span>
          </p>
        </div>
        <div class="about-images">
        </div>
      </div>

      <%# -------- mobile --------  %>
      <div class="martir-container d-sm-none main-about-mobile d-flex flex-column justify-content-between align-items-center">
        <div class="about-images-mobile">
        </div>
        <div class="about-bandeira-mobile">
          <p>"In 1972, I went to the bus station and took a bus to Ouro Preto to meet Nello. I rang the doorbell of his house in Largo do Rosario, introduced myself as a simple schoolboy, spoke of my interest in purchasing one of his paintings, even if that meant to spend my allowance money. Acknowledging the situation, he received me kindly and brought me a beautiful sunset in Ouro Preto painting, asking if eight installments would be fine. This painting is part of this collection now open to the public."
            <br><br> <span style="font-style:normal">— Tadeu Bandeira</span>
        </div>
      </div>
      <%# ------------------------  %>


      <div class="breath"></div>


      <div class="d-flex loop justify-content-center align-items-center">
      </div>

      <div class="artistas-obras bg-cream d-flex justify-content-center align-items-center">
        <%= image_tag "artistas-obras.svg", class:"d-none d-lg-block artistas-obras-img-desktop" %>
        <%= image_tag "artistas-obras-mobile.svg", class:"d-block d-lg-none artistas-obras-img-mobile" %>
      </div>

      <div class="martir-container accordion accordion-flush" id="accordionFlushExample">

        <% @artists.each do |artist| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="flush-heading<%= artist.id %>">
            <button class="artist-line accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse<%= artist.id %>" aria-expanded="false" aria-controls="flush-collapse<%= artist.id %>">
              <%= artist.name %>
            </button>
          </h2>
          <div id="flush-collapse<%= artist.id %>" class="accordion-collapse collapse" aria-labelledby="flush-heading<%= artist.id %>" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body p-0 pt-4 pb-4 d-flex justify-content-between">
                <% if artist.photos.count >= 1 %>
                  <div class="artist-works d-flex align-items-start">
                    <% artist.photos.each do |photo| %>
                    <%= cl_image_tag photo.key %>
                    <% end %>
                  </div>
                <% end %>
                <div class="artist-bio">
                  <p><%= simple_format(artist.bio) %></p>
                  <br>
                  <%= link_to artist_path(artist) do %>
                  <span class="btn-vermais">MORE</span> <%= image_tag('arrow.svg') %>
                  <% end %>
                </div>

              </div>

          </div>
        </div>
        <% end %>


      </div>

      <div class="martir-container box-tragaluz">
        <div class="d-flex justify-content-between box-tragaluz-content bg-cream p-4 p-sm-5" style="border-radius:24px;">

            <h3>TRAGALUZ <br> INSTITUTE</h3>

              <p>
                How to form ideas, create, criticize, grow and, if necessary, transform them into knowledge? And how to know if we are not part of a continuous and multiform educational process, using the most diverse and different resources?
                <br><br>
                Tragaluz Institute collaborates in a practical an active way in this scenario with artistic and cultural pieces of art, exhibitions, lectures, debates and a series of social and educational initiatives with actions since earty childhood.
                <br><br>
                Located in the historic city of Tiradentes, it is a non-profit institute, whose actions aim to encourage other with a similar neture, in full exercise of social responsibility and citizenship.
              </p>

        </div>
      </div>
    </div>
</div>

app/views/artists/new.html.erb
<div class="navigation">
  <div class="martir-container d-flex justify-content-between align-items-center">
      <%= link_to image_tag("martir_logo_sm.svg"), root_path %>
      <div class="menu m-0 p-0 d-flex">
        <%# link_to "SOBRE", sobre_path, class:"hover-underline-animation" %>
        <%# link_to "INSTITUTO TRAGALUZ", sobre_path, class:"hover-underline-animation" %>
      </div>
    </div>
</div>

<div class="martir-container d-flex" style="padding-top: 120px;">
  <h4 style="margin-right: 32px;">Novos <br>Artistas</h4>
  <%= render "form", artist: @artist %>
</div>

app/views/artists/show.html.erb
<div class="navigation">
  <div class="martir-container d-flex justify-content-between align-items-center">
      <%= link_to image_tag("martir_logo_sm.svg"), root_path %>
      <div class="menu m-0 p-0 d-flex">
        <%= link_to "SOBRE", sobre_path, class:"hover-underline-animation" %>
        <%= link_to "INSTITUTO TRAGALUZ", sobre_path, class:"hover-underline-animation" %>
      </div>
    </div>
</div>

<div class="martir-container">

    <div class="row pt-5">
      <div class="col-12 col-sm-5 col-lg-6 artist-name">
        <%= @artist.name %>
      </div>
    </div>

    <div class="d-none d-sm-flex row pt-3">
      <div class="col-sm-5 col-lg-6 artist-menu">
          <% if @artist.photos.count > 1 %>
            <div class="d-none d-sm-block artist-menu-title">
              <% if @artist.detail == true %>
                detalhes de obras
              <% else %>
                obras
              <% end %>
            </div>
          <% elsif @artist.photos.count == 1 %>
            <div class="d-none d-sm-block artist-menu-title">
              <% if @artist.detail == true %>
                detalhe de obra
              <% else %>
                obra
              <% end %>
            </div>
          <% elsif @artist.photos.count == 0 %>
            <div class="artist-menu-title"></div>
          <% end %>
      </div>
      <div class="col-sm-6 col-lg-5 offset-1 artist-menu d-flex justify-content-between nav nav-pills mb-3" id="pills-tab" role="tablist">
        <% if @artist.about != "" %>
          <div class="nav-item" role="presentation">
            <button class="nav-link artist-menu-title active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true" style="color:black;">Biografia</button>
          </div>
        <% end %>
        <% if @artist.critica != "" %>
          <div class="nav-item" role="presentation">
            <button class="nav-link artist-menu-title" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false" style="color:black;">Críticas</button>
          </div>
        <% end %>
        <% if @artist.exposicao != "" %>
          <div class="nav-item" role="presentation">
            <button class="nav-link artist-menu-title" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false" style="color:black;">Exposições</button>
          </div>
        <% end %>
      </div>
    </div>

    <div class="d-none d-sm-flex row">
        <% if @artist.photos.count > 1 %>
          <div id="carouselExampleControls" class="col-sm-5 col-lg-6 carousel slide" data-bs-ride="carousel">
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span aria-hidden="true"> <%= image_tag "arrow-img.svg", class:"prev-icon" %> </span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span aria-hidden="true"> <%= image_tag "arrow-img.svg", class:"next-icon" %> </span>
            </button>
            <div class="carousel-inner mt-3">
              <% @artist.photos.each do |photo| %>
                <% if photo == @artist.photos.first %>
              <div class="carousel-item active" data-bs-interval="4000">
                <%= cl_image_tag photo.key, class:"d-block w-100" %>
              </div>
                <% else %>
              <div class="carousel-item" data-bs-interval="4000">
                <%= cl_image_tag photo.key, class:"d-block w-100" %>
              </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if @artist.photos.count == 1 %>
          <div class="col-sm-5 col-lg-6" >
            <%= cl_image_tag @artist.photos.first.key, class:"d-block w-100" %>
          </div>
        <% end %>

        <% if @artist.photos.count < 1 %>
          <div class="col-sm-5 col-lg-6" >
          </div>
        <% end %>

        <div class="col-sm-6 col-lg-5 offset-1 tab-content p-0 mt-3" id="pills-tabContent">
          <% if @artist.about != nil %>
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
              <%= simple_format(@artist.about) %>
            </div>
          <% end %>
          <% if @artist.critica != nil %>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
              <%= simple_format(@artist.critica) %>
            </div>
          <% end %>
          <% if @artist.exposicao != nil %>
            <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
              <%= simple_format(@artist.exposicao) %>
            </div>
          <% end %>
        </div>
    </div>

    <%# MOBILE  %>

    <div class="mt-4 d-block d-sm-none">

      <% if @artist.photos.count > 1 %>
          <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">

            <div class="carousel-inner mt-3">
              <% @artist.photos.each do |photo| %>
                <% if photo == @artist.photos.first %>
              <div class="carousel-item active" data-bs-interval="4000">
                <%= cl_image_tag photo.key, class:"d-block w-100" %>
              </div>
                <% else %>
              <div class="carousel-item" data-bs-interval="4000">
                <%= cl_image_tag photo.key, class:"d-block w-100" %>
              </div>
                <% end %>
              <% end %>
            </div>
          </div>
      <% end %>

        <% if @artist.photos.count == 1 %>
          <div>
            <%= cl_image_tag @artist.photos.first.key, class:"d-block w-100" %>
          </div>
        <% end %>

        <% if @artist.photos.count < 1 %>
          <div>
          </div>
        <% end %>

      <div class="mt-4 artist-menu d-flex justify-content-between nav nav-pills mb-3" id="pills-tab" role="tablist">
        <div class="nav-item" role="presentation">
          <button class="nav-link artist-menu-title active" id="pills-homemobile-tab" data-bs-toggle="pill" data-bs-target="#pills-homemobile" type="button" role="tab" aria-controls="pills-homemobile" aria-selected="true" style="color:black;">Biografia</button>
        </div>
        <div class="nav-item" role="presentation">
          <button class="nav-link artist-menu-title" id="pills-profilemobile-tab" data-bs-toggle="pill" data-bs-target="#pills-profilemobile" type="button" role="tab" aria-controls="pills-profilemobile" aria-selected="false" style="color:black;">Críticas</button>
        </div>
        <div class="nav-item" role="presentation">
          <button class="nav-link artist-menu-title" id="pills-contactmobile-tab" data-bs-toggle="pill" data-bs-target="#pills-contactmobile" type="button" role="tab" aria-controls="pills-contactmobile" aria-selected="false" style="color:black;">Exposições</button>
        </div>
      </div>

      <div class="tab-content p-0 mt-3" id="pills-tabContent">
          <% if @artist.about != nil %>
            <div class="tab-pane fade show active" id="pills-homemobile" role="tabpanel" aria-labelledby="pills-homemobile-tab">
              <%= simple_format(@artist.about) %>
            </div>
          <% end %>
          <% if @artist.critica != nil %>
            <div class="tab-pane fade" id="pills-profilemobile" role="tabpanel" aria-labelledby="pills-profilemobile-tab">
              <%= simple_format(@artist.critica) %>
            </div>
          <% end %>
          <% if @artist.exposicao != nil %>
            <div class="tab-pane fade" id="pills-contactmobile" role="tabpanel" aria-labelledby="pills-contactmobile-tab">
              <%= simple_format(@artist.exposicao) %>
            </div>
          <% end %>
      </div>
    </div>

</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Martir</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag %>
    </head>

  <body>
  <%# render "shared/navbar" %>
  <%# render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="martir-container d-flex justify-content-between">
    <%= image_tag "martir_logo_footer.svg" %>
    <div class="d-flex footer-infos justify-content-between">
      <div class="mb-3"> FUNCIONAMENTO:  <br> Qui à Sáb <br> 10h às 17h</div>
      <div class="mb-3"> CONTATO:  <br> info@martir.org <br>@martir.tiradentes</div>
      <div class="mb-3"> ENDEREÇO: <br>Rua Direita, 44 – Centro Histórico<br>Tiradentes – MG / Brasil</div>
    </div>
  </div>
</div>